Module6 task1
htmlacademy-php/1470531-yeticave-12 pull request #10
Opened 2020-12-19 10:48 UTC by ivanov-alexey

2020-12-21 17:59 UTC, nkolosov commented on templates/layout.php
> +function redirect()
Функций и прочей логики не должно быть в шаблонах, это всё надо делать в скриптах с логикой.

2020-12-21 18:00 UTC, nkolosov requested changes

2020-12-21 18:00 UTC, nkolosov commented on schema.sql
> +    title           VARCHAR(250)  NOT NULL DEFAULT '',
Кажется, что дефолтных значений в этих полях не должно быть, они все обязательные

2020-12-28 11:06 UTC, nkolosov commented on 404.php
> +    'title' => $page_titles['404'],
Проще сразу передавать нужное значение, а не использовать для этого вспомогательный массив

2020-12-28 11:08 UTC, nkolosov commented on lot.php
> +if (strlen($id)) {
Не очень корректная проверка, что если я передам вот такое значение: `lot.php?id=-100` ?

2020-12-28 11:08 UTC, nkolosov commented on templates/layout.php
> + * @var bool $is_redirect_to_404
А для чего в шаблоне используется `is_redirect_to_404` ?

2020-12-28 11:11 UTC, nkolosov commented on lot.php
> +if ($offer['id']) {
Не нужно вводить дополнительных переменных, достаточно такого примерно алгоритма:
Првоеряем корректность входных данных
Если некорректно - редирект
Загружаем данные из БД
Не найдено - редирект
Выводим данные из шаблона (если мы дошли до этого места, то данные корректны и их удалось загрузить из БД)

2020-12-28 12:34 UTC, ivanov-alexey commented on templates/layout.php
> + * @var bool $is_redirect_to_404
забыл убрать

2020-12-28 13:00 UTC, ivanov-alexey commented on lot.php
> +if ($offer['id']) {
я пробовал посчитать строки с помощью `mysqli_num_rows`, в функции `getOfferById` и у меня всегда возвращается 1, и приходит массив с пустыми значениями, наверное из-за `IFNULL`, который в запросе используется, поэтому добавил проверку `if ($offer['id'])   
![image](https://user-images.githubusercontent.com/24309928/103215914-ca34af00-4925-11eb-858d-b5f199e21aa1.png)

2020-12-30 05:57 UTC, nkolosov commented on lot.php
> +if ($offer['id']) {
Это происходит из-за использование агреггирующей функции `MAX`, то есть строка в результате всегда возвращается, просто все поля - `null`

Чтобы исправить эту проблему, нужно в запрос добавить ` group by l.id`, тогда пустые строки не будут возвращаться

2021-01-12 08:30 UTC, merged