feat: добавил форматирование цены
htmlacademy-php/1470531-yeticave-12 pull request #4
Opened 2020-11-17 14:11 UTC by ivanov-alexey

2020-11-17 14:56 UTC, nkolosov requested changes

2020-11-17 14:56 UTC, nkolosov commented on index.php
> +function format_price ($price ) {
Лучше вынести функцию в отдельный файл (наподобие `helpers.php`)

Кроме того, по критериям,
Код с поддержкой PHP7 обычно содержит указание на тип параметра и возвращаемого значения (type hint)

Не обязательно:
Д5. Документирование методов.
Все пользовательские функции и методы должны быть задокументированы, используя синтаксис phpDoc.

2020-11-18 12:46 UTC, ivanov-alexey commented on index.php
> +function format_price ($price ) {
поправил

2020-11-23 09:48 UTC, nkolosov requested changes

2020-11-23 09:48 UTC, nkolosov commented on index.php
> +                <li class="promo__item promo__item--boards">
У каждой категории - свой класс (`--boards` и т.п.), подробнее можно посмотреть в`style.css`

2020-11-23 09:48 UTC, nkolosov commented on index.php
>              <li class="promo__item promo__item--boards">
А вот это нужно удалить

2020-11-23 12:15 UTC, ivanov-alexey commented on index.php
> +                <li class="promo__item promo__item--boards">
Хм...есть еще другие варианты, кроме ассоциативного массива типа `['name' => 'Ботинки', 'css_modifier' => 'boots']`? Я так понимаю, у нас потом эти категории в базе данных будут храниться, и мне придется хранить название css класса в базе? Это распространенная практика или 💩?

2020-11-23 12:22 UTC, ivanov-alexey commented on index.php
>              <li class="promo__item promo__item--boards">
done

2020-11-25 08:00 UTC, nkolosov requested changes

2020-11-25 08:00 UTC, nkolosov commented on config.php
> +        'price' => '10999',
Цена - это число, а тут получается строка. Кавычки - это лишнее тут

2020-11-25 08:00 UTC, merged